language: cpp
sudo: false
dist: trusty

notifications:
  email:
    on_success: change
    on_failure: always

matrix:
  include:
  - os: osx
    osx_image: xcode10
    compiler: clang
    env: COMPILER=clang++
    before_install: brew install sdl2
  - os: linux
    compiler: clang
    addons:
      apt:
        sources: ["ubuntu-toolchain-r-test", "llvm-toolchain-trusty-6.0"]
        packages: ["clang-6.0", "g++-7", "libsdl2-dev"]
    env: COMPILER=clang++-6.0
  - os: linux
    compiler: gcc
    addons:
      apt:
        sources: ["ubuntu-toolchain-r-test"]
        packages: ["g++-7", "libsdl2-dev"]
    env: COMPILER=g++-7
    
before_install:
- export CXX=${COMPILER}

script:
- cd build
- cmake -DCMAKE_BUILD_TYPE=Release ..
- make
