version: 1.0.{build}

image: Visual Studio 2017

environment:
  BUILD_DIR: "%APPVEYOR_BUILD_FOLDER%\\build"

platform:
  - Win32

configuration:
  - Release

install:
  - vcpkg install sdl2

before_build:
  - cd %BUILD_DIR%
  - cmake .. -DCMAKE_TOOLCHAIN_FILE=/tools/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=Release -G"Visual Studio 15 2017"

build:
  parallel: true
  verbosity: minimal
